/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uabc.cajeros;

import java.io.File;
import java.util.ArrayList;
import java.util.Queue;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author JesusOmar Leal
 */
public class CajerosIDE extends javax.swing.JFrame {

    /**
     * Creates new form CajerosIDE
     */
    private int tiempoSimulacion = PantallaInicio.getTiempoSimulacion();
    private ArrayList<Caja> cajerosAbiertos = new ArrayList<>();
    private int registroID = 1;

    public CajerosIDE() {
        initComponents();
        System.out.println("El tiempo introducido es:" + tiempoSimulacion);
        limpiarLabels();
        iniciarSimulacion();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InterfazPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CajaR1 = new javax.swing.JLabel();
        CajaR2 = new javax.swing.JLabel();
        CajaR3 = new javax.swing.JLabel();
        CajaN1 = new javax.swing.JLabel();
        CajaN2 = new javax.swing.JLabel();
        CajaN3 = new javax.swing.JLabel();
        CajaN4 = new javax.swing.JLabel();
        CajaN5 = new javax.swing.JLabel();
        CajaN6 = new javax.swing.JLabel();
        CajaN7 = new javax.swing.JLabel();
        CajaN8 = new javax.swing.JLabel();
        CajaN9 = new javax.swing.JLabel();
        CajaN10 = new javax.swing.JLabel();
        ClienteR11 = new javax.swing.JLabel();
        ClienteR12 = new javax.swing.JLabel();
        ClienteR13 = new javax.swing.JLabel();
        ClienteR14 = new javax.swing.JLabel();
        ClienteR15 = new javax.swing.JLabel();
        ClienteR21 = new javax.swing.JLabel();
        ClienteR22 = new javax.swing.JLabel();
        ClienteR23 = new javax.swing.JLabel();
        ClienteR24 = new javax.swing.JLabel();
        ClienteR25 = new javax.swing.JLabel();
        ClienteR31 = new javax.swing.JLabel();
        ClienteR32 = new javax.swing.JLabel();
        ClienteR33 = new javax.swing.JLabel();
        ClienteR34 = new javax.swing.JLabel();
        ClienteR35 = new javax.swing.JLabel();
        ClienteN11 = new javax.swing.JLabel();
        ClienteN12 = new javax.swing.JLabel();
        ClienteN13 = new javax.swing.JLabel();
        ClienteN14 = new javax.swing.JLabel();
        ClienteN15 = new javax.swing.JLabel();
        ClienteN21 = new javax.swing.JLabel();
        ClienteN22 = new javax.swing.JLabel();
        ClienteN23 = new javax.swing.JLabel();
        ClienteN24 = new javax.swing.JLabel();
        ClienteN25 = new javax.swing.JLabel();
        ClienteN31 = new javax.swing.JLabel();
        ClienteN32 = new javax.swing.JLabel();
        ClienteN33 = new javax.swing.JLabel();
        ClienteN34 = new javax.swing.JLabel();
        ClienteN35 = new javax.swing.JLabel();
        ClienteN41 = new javax.swing.JLabel();
        ClienteN42 = new javax.swing.JLabel();
        ClienteN43 = new javax.swing.JLabel();
        ClienteN44 = new javax.swing.JLabel();
        ClienteN45 = new javax.swing.JLabel();
        ClienteN51 = new javax.swing.JLabel();
        ClienteN52 = new javax.swing.JLabel();
        ClienteN53 = new javax.swing.JLabel();
        ClienteN54 = new javax.swing.JLabel();
        ClienteN55 = new javax.swing.JLabel();
        ClienteN61 = new javax.swing.JLabel();
        ClienteN62 = new javax.swing.JLabel();
        ClienteN63 = new javax.swing.JLabel();
        ClienteN64 = new javax.swing.JLabel();
        ClienteN65 = new javax.swing.JLabel();
        ClienteN71 = new javax.swing.JLabel();
        ClienteN72 = new javax.swing.JLabel();
        ClienteN73 = new javax.swing.JLabel();
        ClienteN74 = new javax.swing.JLabel();
        ClienteN75 = new javax.swing.JLabel();
        ClienteN81 = new javax.swing.JLabel();
        ClienteN82 = new javax.swing.JLabel();
        ClienteN83 = new javax.swing.JLabel();
        ClienteN84 = new javax.swing.JLabel();
        ClienteN85 = new javax.swing.JLabel();
        ClienteN91 = new javax.swing.JLabel();
        ClienteN92 = new javax.swing.JLabel();
        ClienteN93 = new javax.swing.JLabel();
        ClienteN94 = new javax.swing.JLabel();
        ClienteN95 = new javax.swing.JLabel();
        ClienteN101 = new javax.swing.JLabel();
        ClienteN102 = new javax.swing.JLabel();
        ClienteN103 = new javax.swing.JLabel();
        ClienteN104 = new javax.swing.JLabel();
        ClienteN105 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InterfazPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        InterfazPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 10, 430));

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel1.setText("Cajas Rapidas");
        InterfazPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel2.setText("Cajas Normales");
        InterfazPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel5.setText("Caja 3");
        InterfazPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel3.setText("Caja 2");
        InterfazPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel4.setText("Caja 1");
        InterfazPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel8.setText("Caja 3");
        InterfazPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel6.setText("Caja 1");
        InterfazPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel7.setText("Caja 2");
        InterfazPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel9.setText("Caja 4");
        InterfazPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel10.setText("Caja 5");
        InterfazPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel11.setText("Caja 6");
        InterfazPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel12.setText("Caja 7");
        InterfazPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel13.setText("Caja 8");
        InterfazPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel14.setText("Caja 10");
        InterfazPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, -1, -1));

        jLabel15.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel15.setText("Caja 9");
        InterfazPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, -1, -1));

        CajaR1.setBackground(new java.awt.Color(255, 255, 255));
        CajaR1.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux1.png")); // NOI18N
        InterfazPanel.add(CajaR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 60));

        CajaR2.setBackground(new java.awt.Color(255, 255, 255));
        CajaR2.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux1.png")); // NOI18N
        InterfazPanel.add(CajaR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 60));

        CajaR3.setBackground(new java.awt.Color(255, 255, 255));
        CajaR3.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux2.png")); // NOI18N
        InterfazPanel.add(CajaR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 60));

        CajaN1.setBackground(new java.awt.Color(255, 255, 255));
        CajaN1.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux1.png")); // NOI18N
        InterfazPanel.add(CajaN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 60));

        CajaN2.setBackground(new java.awt.Color(255, 255, 255));
        CajaN2.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux1.png")); // NOI18N
        InterfazPanel.add(CajaN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, 60));

        CajaN3.setBackground(new java.awt.Color(255, 255, 255));
        CajaN3.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux2.png")); // NOI18N
        InterfazPanel.add(CajaN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, 60));

        CajaN4.setBackground(new java.awt.Color(255, 255, 255));
        CajaN4.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux2.png")); // NOI18N
        InterfazPanel.add(CajaN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, 60));

        CajaN5.setBackground(new java.awt.Color(255, 255, 255));
        CajaN5.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux2.png")); // NOI18N
        InterfazPanel.add(CajaN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, 60));

        CajaN6.setBackground(new java.awt.Color(255, 255, 255));
        CajaN6.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux1.png")); // NOI18N
        InterfazPanel.add(CajaN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, 60));

        CajaN7.setBackground(new java.awt.Color(255, 255, 255));
        CajaN7.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux1.png")); // NOI18N
        InterfazPanel.add(CajaN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, -1, 60));

        CajaN8.setBackground(new java.awt.Color(255, 255, 255));
        CajaN8.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux2.png")); // NOI18N
        InterfazPanel.add(CajaN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, -1, 60));

        CajaN9.setBackground(new java.awt.Color(255, 255, 255));
        CajaN9.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux1.png")); // NOI18N
        InterfazPanel.add(CajaN9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, -1, 60));

        CajaN10.setBackground(new java.awt.Color(255, 255, 255));
        CajaN10.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cajeroaux2.png")); // NOI18N
        InterfazPanel.add(CajaN10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, -1, 60));

        ClienteR11.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteR11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 50));

        ClienteR12.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente2.png")); // NOI18N
        InterfazPanel.add(ClienteR12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 50));

        ClienteR13.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteR13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 70, 50));

        ClienteR14.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteR14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 50));

        ClienteR15.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteR15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 70, 50));

        ClienteR21.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\assets\\cliente2.png")); // NOI18N
        InterfazPanel.add(ClienteR21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 70, 50));

        ClienteR22.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteR22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 70, 50));

        ClienteR23.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente2.png")); // NOI18N
        InterfazPanel.add(ClienteR23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 70, 50));

        ClienteR24.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteR24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 70, 50));

        ClienteR25.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteR25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 70, 50));

        ClienteR31.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente2.png")); // NOI18N
        InterfazPanel.add(ClienteR31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 70, 50));

        ClienteR32.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteR32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 70, 50));

        ClienteR33.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteR33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 70, 50));

        ClienteR34.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteR34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 70, 50));

        ClienteR35.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteR35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 70, 50));

        ClienteN11.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 70, 50));

        ClienteN12.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 70, 50));

        ClienteN13.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 70, 50));

        ClienteN14.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente2.png")); // NOI18N
        InterfazPanel.add(ClienteN14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 70, 50));

        ClienteN15.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 70, 50));

        ClienteN21.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 70, 50));

        ClienteN22.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 70, 50));

        ClienteN23.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 70, 50));

        ClienteN24.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 70, 50));

        ClienteN25.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente2.png")); // NOI18N
        InterfazPanel.add(ClienteN25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 70, 50));

        ClienteN31.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 70, 50));

        ClienteN32.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN32, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 70, 50));

        ClienteN33.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente2.png")); // NOI18N
        InterfazPanel.add(ClienteN33, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 70, 50));

        ClienteN34.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN34, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 70, 50));

        ClienteN35.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN35, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 70, 50));

        ClienteN41.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN41, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 70, 50));

        ClienteN42.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN42, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 70, 50));

        ClienteN43.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN43, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 70, 50));

        ClienteN44.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN44, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 70, 50));

        ClienteN45.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN45, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 70, 50));

        ClienteN51.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN51, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 70, 50));

        ClienteN52.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN52, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 70, 50));

        ClienteN53.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN53, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 70, 50));

        ClienteN54.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN54, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 70, 50));

        ClienteN55.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN55, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 70, 50));

        ClienteN61.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN61, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 70, 50));

        ClienteN62.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN62, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 70, 50));

        ClienteN63.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN63, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 70, 50));

        ClienteN64.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN64, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 70, 50));

        ClienteN65.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN65, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 70, 50));

        ClienteN71.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN71, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 70, 50));

        ClienteN72.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente2.png")); // NOI18N
        InterfazPanel.add(ClienteN72, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 70, 50));

        ClienteN73.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN73, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 70, 50));

        ClienteN74.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente2.png")); // NOI18N
        InterfazPanel.add(ClienteN74, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 70, 50));

        ClienteN75.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN75, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 70, 50));

        ClienteN81.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN81, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 70, 50));

        ClienteN82.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN82, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 70, 50));

        ClienteN83.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN83, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 70, 50));

        ClienteN84.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN84, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 70, 50));

        ClienteN85.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN85, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 70, 50));

        ClienteN91.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN91, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 70, 50));

        ClienteN92.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN92, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, 70, 50));

        ClienteN93.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN93, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 250, 70, 50));

        ClienteN94.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN94, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 70, 50));

        ClienteN95.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN95, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, 70, 50));

        ClienteN101.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN101, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 130, 70, 50));

        ClienteN102.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN102, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 190, 70, 50));

        ClienteN103.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN103, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 250, 70, 50));

        ClienteN104.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente2.png")); // NOI18N
        InterfazPanel.add(ClienteN104, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 310, 70, 50));

        ClienteN105.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\src\\main\\java\\com\\uabc\\cajeros\\assets\\cliente1.png")); // NOI18N
        InterfazPanel.add(ClienteN105, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 370, 70, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InterfazPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InterfazPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CajerosIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CajerosIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CajerosIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CajerosIDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CajerosIDE().setVisible(true);
            }
        });
    }

    public JLabel obtenerCajas(int indice) {

        switch (indice) {
            case 1:
                return CajaR1;
            case 2:
                return CajaR2;
            case 3:
                return CajaR3;
            case 4:
                return CajaN1;
            case 5:
                return CajaN2;
            case 6:
                return CajaN3;
            case 7:
                return CajaN4;
            case 8:
                return CajaN5;
            case 9:
                return CajaN6;
            case 10:
                return CajaN7;
            case 11:
                return CajaN8;
            case 12:
                return CajaN9;
            case 13:
                return CajaN10;

            default:
                throw new IllegalArgumentException("Indice Fuera de Rango");
        }

    }

    public JLabel obtenerClientesCajasRapidas(int indice) {

        switch (indice) {
            case 1:
                return ClienteR11;
            case 2:
                return ClienteR12;
            case 3:
                return ClienteR13;
            case 4:
                return ClienteR14;
            case 5:
                return ClienteR15;
            case 6:
                return ClienteR21;
            case 7:
                return ClienteR22;
            case 8:
                return ClienteR23;
            case 9:
                return ClienteR24;
            case 10:
                return ClienteR25;
            case 11:
                return ClienteR31;
            case 12:
                return ClienteR32;
            case 13:
                return ClienteR33;
            case 14:
                return ClienteR34;
            case 15:
                return ClienteR35;

            default:
                throw new IllegalArgumentException("Indice Fuera de Rango");
        }

    }

    public JLabel obtenerClientesCajasNormales(int indice) {

        switch (indice) {
            case 1:
                return ClienteN11;
            case 2:
                return ClienteN12;
            case 3:
                return ClienteN13;
            case 4:
                return ClienteN14;
            case 5:
                return ClienteN15;
            case 6:
                return ClienteN21;
            case 7:
                return ClienteN22;
            case 8:
                return ClienteN23;
            case 9:
                return ClienteN24;
            case 10:
                return ClienteN25;
            case 11:
                return ClienteN31;
            case 12:
                return ClienteN32;
            case 13:
                return ClienteN33;
            case 14:
                return ClienteN34;
            case 15:
                return ClienteN35;
            case 16:
                return ClienteN41;
            case 17:
                return ClienteN42;
            case 18:
                return ClienteN43;
            case 19:
                return ClienteN44;
            case 20:
                return ClienteN45;
            case 21:
                return ClienteN51;
            case 22:
                return ClienteN52;
            case 23:
                return ClienteN53;
            case 24:
                return ClienteN54;
            case 25:
                return ClienteN55;
            case 26:
                return ClienteN61;
            case 27:
                return ClienteN62;
            case 28:
                return ClienteN63;
            case 29:
                return ClienteN64;
            case 30:
                return ClienteN65;
            case 31:
                return ClienteN71;
            case 32:
                return ClienteN72;
            case 33:
                return ClienteN73;
            case 34:
                return ClienteN74;
            case 35:
                return ClienteN75;
            case 36:
                return ClienteN81;
            case 37:
                return ClienteN82;
            case 38:
                return ClienteN83;
            case 39:
                return ClienteN84;
            case 40:
                return ClienteN85;
            case 41:
                return ClienteN91;
            case 42:
                return ClienteN92;
            case 43:
                return ClienteN93;
            case 44:
                return ClienteN94;
            case 45:
                return ClienteN95;
            case 46:
                return ClienteN101;
            case 47:
                return ClienteN102;
            case 48:
                return ClienteN103;
            case 49:
                return ClienteN104;
            case 50:
                return ClienteN105;

            default:
                throw new IllegalArgumentException("Indice Fuera de Rango");
        }

    }

    private void setImagen(JLabel label, String rutaImagen) {

        File archivoImagen = new File(rutaImagen);

        if (archivoImagen.exists()) {

            label.setIcon(new ImageIcon(rutaImagen));

        } else {

            JOptionPane.showMessageDialog(this, "Imagen no encontrada", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarLabels() {
        for (int i = 1; i <= 13; i++) {
            setImagen(obtenerCajas(i), "assets\\\\cajeroCerrado.png");
        }

        for (int i = 1; i <= 15; i++) {
            setImagen(obtenerClientesCajasRapidas(i), "assets\\\\ausente.png");
        }

        for (int i = 1; i <= 50; i++) {
            setImagen(obtenerClientesCajasNormales(i), "assets\\\\ausente.png");
        }

    }

    private void generarCajeroImagen(int indice) {

        Random random = new Random();

        if (random.nextBoolean()) {
            
            setImagen(obtenerCajas(indice), "assets\\\\cajeroaux2.png");
        } else {
            setImagen(obtenerCajas(indice), "assets\\\\cajeroaux1.png");
        }

    }

    private void generarClienteCajaRapidaImagen(int indice) {

        Random random = new Random();

        if (random.nextBoolean()) {
            setImagen(obtenerClientesCajasRapidas(indice), "assets\\\\cajeroaux2.png");
        } else {
            setImagen(obtenerClientesCajasRapidas(indice), "assets\\\\cajeroaux1.png");
        }

    }

    private void generarClienteCajaNormalImagen(int indice) {

        Random random = new Random();

        if (random.nextBoolean()) {
            setImagen(obtenerClientesCajasNormales(indice), "assets\\\\cajeroaux2.png");
        } else {
            setImagen(obtenerClientesCajasNormales(indice), "assets\\\\cajeroaux1.png");
        }

    }

    private void imprimirCajas() {
        for(int i=1;i<cajerosAbiertos.size();i++){
            
        }
    }

    private void imprimirCliente(Queue<Cliente> cola) {

    }

    private void crearCajaNueva(Cliente cliente) {
        registroID++;
        Caja nuevaCaja = new Caja(cajerosAbiertos.get(cajerosAbiertos.size() + 1).isTipoCaja(), registroID);
        nuevaCaja.getCola().add(cliente);
        cajerosAbiertos.add(nuevaCaja);
        System.out.println("Numero de Cajas Abiertas= " + cajerosAbiertos.size());
    }

    private void crearCliente(Caja cajaActual) {

        Cliente cliente = new Cliente();

        if (cliente.getNumArticulos() <= 10 && !cajaActual.isTipoCaja()) {
            if (cajaActual.getCola().size() < 5) {

                cajaActual.getCola().add(cliente);

            } else {
                crearCajaNueva(cliente);
            }
        } else if (cliente.getNumArticulos() >= 11 && cajaActual.isTipoCaja()) {
            if (cajaActual.getCola().size() < 5) {
                cajaActual.getCola().add(cliente);
            } else {
                crearCajaNueva(cliente);
            }
        }

    }

    public void restarTiempo() {

        this.tiempoSimulacion -= 1000;

    }

    private void iniciarSimulacion() {

        //Aqui empieza la simulacion 
        cajerosAbiertos.add(new Caja(false, registroID));
        registroID++;
        cajerosAbiertos.add(new Caja(true, registroID));

        Timer timer = new Timer();

        TimerTask ejecutar = new TimerTask() {
            @Override
            public void run() {

                System.out.println("Tiempo Restante=" + tiempoSimulacion);

                for (Caja caja : cajerosAbiertos) {
                    
                    
                    
                    crearCliente(caja);

                }

                if (tiempoSimulacion <= 0) {

                    timer.cancel();

                    JOptionPane.showMessageDialog(null, "Simulación completa exitosamente", "Simulación Completa", JOptionPane.INFORMATION_MESSAGE);
                } else {

                    restarTiempo();
                }
            }
        };

        timer.schedule(ejecutar, 0, 1000);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CajaN1;
    private javax.swing.JLabel CajaN10;
    private javax.swing.JLabel CajaN2;
    private javax.swing.JLabel CajaN3;
    private javax.swing.JLabel CajaN4;
    private javax.swing.JLabel CajaN5;
    private javax.swing.JLabel CajaN6;
    private javax.swing.JLabel CajaN7;
    private javax.swing.JLabel CajaN8;
    private javax.swing.JLabel CajaN9;
    private javax.swing.JLabel CajaR1;
    private javax.swing.JLabel CajaR2;
    private javax.swing.JLabel CajaR3;
    private javax.swing.JLabel ClienteN101;
    private javax.swing.JLabel ClienteN102;
    private javax.swing.JLabel ClienteN103;
    private javax.swing.JLabel ClienteN104;
    private javax.swing.JLabel ClienteN105;
    private javax.swing.JLabel ClienteN11;
    private javax.swing.JLabel ClienteN12;
    private javax.swing.JLabel ClienteN13;
    private javax.swing.JLabel ClienteN14;
    private javax.swing.JLabel ClienteN15;
    private javax.swing.JLabel ClienteN21;
    private javax.swing.JLabel ClienteN22;
    private javax.swing.JLabel ClienteN23;
    private javax.swing.JLabel ClienteN24;
    private javax.swing.JLabel ClienteN25;
    private javax.swing.JLabel ClienteN31;
    private javax.swing.JLabel ClienteN32;
    private javax.swing.JLabel ClienteN33;
    private javax.swing.JLabel ClienteN34;
    private javax.swing.JLabel ClienteN35;
    private javax.swing.JLabel ClienteN41;
    private javax.swing.JLabel ClienteN42;
    private javax.swing.JLabel ClienteN43;
    private javax.swing.JLabel ClienteN44;
    private javax.swing.JLabel ClienteN45;
    private javax.swing.JLabel ClienteN51;
    private javax.swing.JLabel ClienteN52;
    private javax.swing.JLabel ClienteN53;
    private javax.swing.JLabel ClienteN54;
    private javax.swing.JLabel ClienteN55;
    private javax.swing.JLabel ClienteN61;
    private javax.swing.JLabel ClienteN62;
    private javax.swing.JLabel ClienteN63;
    private javax.swing.JLabel ClienteN64;
    private javax.swing.JLabel ClienteN65;
    private javax.swing.JLabel ClienteN71;
    private javax.swing.JLabel ClienteN72;
    private javax.swing.JLabel ClienteN73;
    private javax.swing.JLabel ClienteN74;
    private javax.swing.JLabel ClienteN75;
    private javax.swing.JLabel ClienteN81;
    private javax.swing.JLabel ClienteN82;
    private javax.swing.JLabel ClienteN83;
    private javax.swing.JLabel ClienteN84;
    private javax.swing.JLabel ClienteN85;
    private javax.swing.JLabel ClienteN91;
    private javax.swing.JLabel ClienteN92;
    private javax.swing.JLabel ClienteN93;
    private javax.swing.JLabel ClienteN94;
    private javax.swing.JLabel ClienteN95;
    private javax.swing.JLabel ClienteR11;
    private javax.swing.JLabel ClienteR12;
    private javax.swing.JLabel ClienteR13;
    private javax.swing.JLabel ClienteR14;
    private javax.swing.JLabel ClienteR15;
    private javax.swing.JLabel ClienteR21;
    private javax.swing.JLabel ClienteR22;
    private javax.swing.JLabel ClienteR23;
    private javax.swing.JLabel ClienteR24;
    private javax.swing.JLabel ClienteR25;
    private javax.swing.JLabel ClienteR31;
    private javax.swing.JLabel ClienteR32;
    private javax.swing.JLabel ClienteR33;
    private javax.swing.JLabel ClienteR34;
    private javax.swing.JLabel ClienteR35;
    private javax.swing.JPanel InterfazPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
