/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uabc.cajeros;

import javax.swing.JOptionPane;

/**
 *
 * @author JesusOmar Leal
 */
public class PantallaInicio extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicio
     */
    private static int TIEMPOSIMULACION;

    public PantallaInicio() {
        initComponents();
    }

    public static int getTiempoSimulacion() {
        return TIEMPOSIMULACION;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TiempoSimulacionTEXT = new javax.swing.JTextField();
        IniciarB = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        titulo.setText("Simulacion Cajeros");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel1.setText("Tiempo Simulacion(Horas)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 30));

        TiempoSimulacionTEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoSimulacionTEXTActionPerformed(evt);
            }
        });
        jPanel1.add(TiempoSimulacionTEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 90, 30));

        IniciarB.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        IniciarB.setText("Iniciar");
        IniciarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarBActionPerformed(evt);
            }
        });
        jPanel1.add(IniciarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 90, 30));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\Cajeros\\assets\\hola.png")); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TiempoSimulacionTEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoSimulacionTEXTActionPerformed


    }//GEN-LAST:event_TiempoSimulacionTEXTActionPerformed

    private void IniciarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarBActionPerformed
        String texto = TiempoSimulacionTEXT.getText();

        if (!texto.isEmpty()) {
            try {
                this.TIEMPOSIMULACION = Integer.parseInt(texto)*60000;

                CajerosIDE interfazSimulacion = new CajerosIDE();
                interfazSimulacion.setVisible(true);
                interfazSimulacion.setLocationRelativeTo(null);
                
            } catch (NumberFormatException e) {
                
                JOptionPane.showMessageDialog(this, "El valor introducido no es un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                
            }
        } else {
            
            JOptionPane.showMessageDialog(this, "No se introdujo ningún valor", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_IniciarBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarB;
    private javax.swing.JTextField TiempoSimulacionTEXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
